#ifndef DRIVER_GATT_H
#define DRIVER_GATT_H

#include "common.h"
#include "ble_gatt.h"


static name_map_t gatt_status_map = {
    NAME_MAP_ENTRY(BLE_GATT_STATUS_SUCCESS),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_UNKNOWN),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_INVALID),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_INVALID_HANDLE),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_READ_NOT_PERMITTED),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_WRITE_NOT_PERMITTED),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_INVALID_PDU),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_INSUF_AUTHENTICATION),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_REQUEST_NOT_SUPPORTED),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_INVALID_OFFSET),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_INSUF_AUTHORIZATION),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_PREPARE_QUEUE_FULL),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_ATTRIBUTE_NOT_FOUND),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_ATTRIBUTE_NOT_LONG),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_INSUF_ENC_KEY_SIZE),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_INVALID_ATT_VAL_LENGTH),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_UNLIKELY_ERROR),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_INSUF_ENCRYPTION),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_UNSUPPORTED_GROUP_TYPE),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_INSUF_RESOURCES),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_RFU_RANGE1_BEGIN),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_RFU_RANGE1_END),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_APP_BEGIN),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_APP_END),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_RFU_RANGE2_BEGIN),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_RFU_RANGE2_END),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_RFU_RANGE3_BEGIN),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_RFU_RANGE3_END),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_CPS_CCCD_CONFIG_ERROR),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_CPS_PROC_ALR_IN_PROG),
    NAME_MAP_ENTRY(BLE_GATT_STATUS_ATTERR_CPS_OUT_OF_RANGE)
};

class GattCharProps : public BleToJs<ble_gatt_char_props_t>
{
public:
    GattCharProps(ble_gatt_char_props_t *gap_addr) : BleToJs<ble_gatt_char_props_t>(gap_addr) {}
    GattCharProps(v8::Local<v8::Object> js) : BleToJs<ble_gatt_char_props_t>(js) {}
    v8::Local<v8::Object> ToJs();
    ble_gatt_char_props_t *ToNative();
};

class GattCharExtProps : public BleToJs<ble_gatt_char_ext_props_t>
{
public:
    GattCharExtProps(ble_gatt_char_ext_props_t *gap_addr) : BleToJs<ble_gatt_char_ext_props_t>(gap_addr) {}
    GattCharExtProps(v8::Local<v8::Object> js) : BleToJs<ble_gatt_char_ext_props_t>(js) {}
    v8::Local<v8::Object> ToJs();
    ble_gatt_char_ext_props_t *ToNative();
};

extern "C" {
    void init_gatt(v8::Handle<v8::Object> target);
}

#endif
